disabled_rules:
  - line_length
  - trailing_whitespace

opt_in_rules:
  - force_unwrapping
  - empty_count

included:
  - Sources
excluded:
  - Pods
  - Carthage

line_length: 120
type_body_length:
  warning: 200
  error: 300
file_length:
  warning: 400
  error: 800